name: "Render ci-cd pipeline"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
   # schedule:
   #  - cron: '37 10 * * *'
   push:
      branches: [master]
      # Publish semver tags as releases.
      # tags: [ 'latest' ]
   pull_request:
      branches: [master]
   workflow_dispatch:

jobs:
   ci-cd-pipeline:
      runs-on: ubuntu-latest

      steps:
         # Checkout the repository
         # https://github.com/actions/checkout
         - name: Checkout repository
           uses: actions/checkout@v3

         # Render deployments via GitHub actions
         # https://github.com/Bounceapp/render-action
         - name: Deploy Server production to Render
           uses: Bounceapp/render-action@0.6.0
           with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              render-token: ${{ secrets.RENDER_AUTH_TOKEN }}
              service-id: ${{ secrets.RENDER_SITE_ID }}
              retries: 20
              wait: 16000
              sleep: 30000
